# use for local testing
# @localUrl = http://localhost:5000

# use for live testing
@liveUrl = https://smart-focus-tracker.onrender.com

# 1. Check initial state
GET {{liveUrl}}/tasks

###

# 2. Create task
POST {{liveUrl}}/tasks
Content-Type: application/json

{
  "title": "Study backend architecture"
}

###
# 3. Verify creation
# Copy the "_id" from this response for steps 4 & 5
GET {{liveUrl}}/tasks

###

# 4. Update task (replace <TASK_ID_HERE>)
PUT {{liveUrl}}/tasks/<TASK_ID_HERE>
Content-Type: application/json

{
  "title": "Updated task title"
}

###

# 5. Delete task (replace <TASK_ID_HERE>)
DELETE {{liveUrl}}/tasks/<TASK_ID_HERE>

###

# 6. Verify final state
GET {{liveUrl}}/tasks

